# Generated by Django 5.0.6 on 2024-07-15 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pag', '0003_usuario_contrasena_usu'),
    ]

    operations = [
    ]
