# Generated by Django 5.0.6 on 2024-07-15 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pag', '0004_auto_20240715_1810'),
    ]

    operations = [
    ]
