# Generated by Django 5.0.6 on 2024-07-16 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pag', '0005_auto_20240715_1923'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='respuesta_preg',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
